package com.tmca.server;

import org.restlet.Application;
import org.restlet.Restlet;
import org.restlet.routing.Router;


public class SOSApplication extends Application {

	//@Override
	public Restlet createInboundRoot() {
	    Router router = new Router(getContext());
	    // Serve the files generated by the GWT compilation step.
	    //router.attachDefault(new Directory(getContext(), "war:///"));
	    router.attach("/sos", EMLServerResource.class);
	    
	    return router;
	}
	
	
}
